[build]
  publish = "site/public"
  command = "cd site && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["fr"]}

[context.production.environment]
  HUGO_ENV = "production"
